version: '3.8'

services:
  web:
    build: ./back-end
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-end/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=afonso
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=django_dev
  front:
    build: ./front-end
    ports:
      - 8080:8080
    depends_on:
      - web
  sgbd:
    image: dpage/pgadmin4
    ports:
      - "5432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dglan2003@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password123

volumes:
  postgres_data:
  back-end: