# Generated by Django 4.2.3 on 2023-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=20, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Espera'), (2, 'Atendida')], verbose_name='Status')),
                ('tipo', models.IntegerField(choices=[(1, 'Convencional'), (2, 'Preferencial')], verbose_name='Tipo')),
                ('horaEmitida', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('horaChamada', models.DateTimeField(null=True, verbose_name='Data e Hora')),
            ],
            options={
                'verbose_name': 'Senha',
                'verbose_name_plural': 'Senhas',
            },
        ),
    ]
