# Generated by Django 4.2.3 on 2023-12-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='pressaoArterial',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Elevada'), (3, 'Hipertensão Estágio 1'), (4, 'Hipertensão Estágio 2'), (5, 'Crise Hipertensiva')], null=True, verbose_name='Pressão Arterial '),
        ),
    ]
