# Generated by Django 4.2.3 on 2023-12-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0002_alter_pessoa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagem',
            name='estado',
        ),
    ]
