# Generated by Django 4.2.3 on 2023-11-28 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fila', '0002_pessoa_triagem_painelmodel_consulta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PainelModel',
            new_name='Painel',
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='painel',
            options={'verbose_name': 'Painel', 'verbose_name_plural': 'Paineis'},
        ),
        migrations.AlterModelOptions(
            name='triagem',
            options={'verbose_name': 'Triagem', 'verbose_name_plural': 'Triagens'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
