# Generated by Django 4.2.3 on 2023-11-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0003_rename_painelmodel_painel_alter_consulta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fila.pessoa'),
        ),
    ]
