# Generated by Django 4.2.3 on 2023-11-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0004_alter_triagem_atendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='quimadurasGraves',
            field=models.IntegerField(choices=[(1, 'Sim'), (2, 'Não')], verbose_name='Queimaduras Graves.'),
        ),
    ]
